# Generated by "_KEEPER_MONITORING_COMPLETE=bash_source KEEPER-monitoring"
_keeper_monitoring_completion() {
    local IFS=$'\n'
    local response

    response=$(env COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD=$COMP_CWORD _KEEPER_MONITORING_COMPLETE=bash_complete $1)

    for completion in $response; do
        IFS=',' read type value <<< "$completion"

        if [[ $type == 'dir' ]]; then
            COMREPLY=()
            compopt -o dirnames
        elif [[ $type == 'file' ]]; then
            COMREPLY=()
            compopt -o default
        elif [[ $type == 'plain' ]]; then
            COMPREPLY+=($value)
        fi
    done

    return 0
}

_keeper_monitoring_completion_setup() {
    complete -o nosort -F _keeper_monitoring_completion keeper-monitoring
}

_keeper_monitoring_completion_setup;
