name: Update base images

run-name: ${{ github.workflow }}_${{ inputs.clickhouse_version }}

on:
  workflow_dispatch:
    inputs:
      clickhouse_version:
        description: 'ClickHouse version'
        required: true
        type: string
        default: "latest"

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    env:
      CLICKHOUSE_VERSIONS: ${{ inputs.clickhouse_version }}
    steps:
      - uses: actions/checkout@v4
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push base images
        uses: docker/bake-action@v4
        with:
          files: tests/bake.hcl
          push: true
